require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/orderdetails", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Orderdetail. As you add validations to Orderdetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Orderdetail.create! valid_attributes
      get orderdetails_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      orderdetail = Orderdetail.create! valid_attributes
      get orderdetail_url(orderdetail)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_orderdetail_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      orderdetail = Orderdetail.create! valid_attributes
      get edit_orderdetail_url(orderdetail)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Orderdetail" do
        expect {
          post orderdetails_url, params: { orderdetail: valid_attributes }
        }.to change(Orderdetail, :count).by(1)
      end

      it "redirects to the created orderdetail" do
        post orderdetails_url, params: { orderdetail: valid_attributes }
        expect(response).to redirect_to(orderdetail_url(Orderdetail.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Orderdetail" do
        expect {
          post orderdetails_url, params: { orderdetail: invalid_attributes }
        }.to change(Orderdetail, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post orderdetails_url, params: { orderdetail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested orderdetail" do
        orderdetail = Orderdetail.create! valid_attributes
        patch orderdetail_url(orderdetail), params: { orderdetail: new_attributes }
        orderdetail.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the orderdetail" do
        orderdetail = Orderdetail.create! valid_attributes
        patch orderdetail_url(orderdetail), params: { orderdetail: new_attributes }
        orderdetail.reload
        expect(response).to redirect_to(orderdetail_url(orderdetail))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        orderdetail = Orderdetail.create! valid_attributes
        patch orderdetail_url(orderdetail), params: { orderdetail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested orderdetail" do
      orderdetail = Orderdetail.create! valid_attributes
      expect {
        delete orderdetail_url(orderdetail)
      }.to change(Orderdetail, :count).by(-1)
    end

    it "redirects to the orderdetails list" do
      orderdetail = Orderdetail.create! valid_attributes
      delete orderdetail_url(orderdetail)
      expect(response).to redirect_to(orderdetails_url)
    end
  end
end
